SET IDENTITY_INSERT [TOP].DBO.CITY  OFF;
INSERT INTO [TOP].dbo.CITY(ID, NAME, ZIPCODE, ZIPPLUS, STATECODE, LATITUDE, LONGITUDE)
SELECT     ID, NAME, ZIPCODE, ZIPPLUS, STATECODE, LATITUDE, LONGITUDE
FROM         CITY AS CITY_1
WHERE     (ZIPCODE IN ('37086', '75156'));